version: "3"
services:

  test:
    build:
      dockerfile: Dockerfile
      context: ./
    container_name: test
    ports:
      - "6022:6022"
    restart: always
   
    volumes:
      - .:/app
      - /app/test/node_modules

  
  
